backend:
  name: github
  branch: main
  repo: paulohp/jessicathings.com
  site_domain: https://jessicathings-com.vercel.app/
  base_url: https://jessicathings-com.vercel.app/
  auth_endpoint: oauth

media_library:
  name: cloudinary
  config:
    cloud_name: dnk8j20ch
    api_key: 796316847451711

# media_folder: src/assets/img
# public_folder: src/assets/img

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "src/content/blog" 
    create: true 
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "ogImage", name: "ogImage", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
